export enum BookmarksTag {
  MARKETING = "Marketing",
  COPYWRITING = "Copywriting",
  UX = "User Experience",
  BOOTSTRAPPING = "Bootstrapping",
  SOFTWARE_ENGINEERING = "Software Engineering",
  DOCUMENTATION = "Documentation",
  STORY_TIME = "Story Time",
  VIDEO = "Video",
  BLOG = "Blog",
  GROWTH = "Growth",
  PODCAST = "Podcast",
  CAREER = "Career",
  PRODUCT_MANAGEMENT = "Product Management",
  TOOLS = "Tools",
  NEXTJS = "Next.js",
  REACT = "React.js",
  JAVASCRIPT = "JavaScript",
  NODE_JS = "Node.js",
  TYPESCRIPT = "TypeScript",
  SEO = "SEO",
  SALES = "Sales",
}

export type BookmarksTags = Array<BookmarksTag>;
